//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

mod utils;

pub mod prelude;

pub mod collection_data;
pub mod device;
pub mod device_realtime_data;
pub mod element_type;
pub mod history;
pub mod info;
pub mod info_area;
pub mod permission;
pub mod prediction;
pub mod region;
pub mod role;
pub mod role_permission;
pub mod task;
pub mod user;
pub mod user_role;
pub mod warn;
pub mod weather_condition;

seaography::register_entity_modules!([
    device,
    task,
    role,
    permission,
    user_role,
    role_permission,
    region,
    element_type,
    history,
    prediction,
    info,
    info_area,
    warn,
    weather_condition,
    collection_data,
]);
